# Generated by Django 5.2.7 on 2025-10-26 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Drug Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_code", models.CharField(max_length=50, unique=True)),
                ("generic_name", models.CharField(max_length=200)),
                ("brand_name", models.CharField(max_length=200)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("CREAM", "Cream/Ointment"),
                            ("DROPS", "Drops"),
                            ("INHALER", "Inhaler"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(help_text="e.g., 500mg, 10ml", max_length=50),
                ),
                ("manufacturer", models.CharField(max_length=200)),
                ("quantity_in_stock", models.IntegerField(default=0)),
                (
                    "reorder_level",
                    models.IntegerField(
                        default=10, help_text="Alert when stock falls below this"
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("side_effects", models.TextField(blank=True)),
                ("storage_instructions", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.drugcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["brand_name"],
            },
        ),
        migrations.CreateModel(
            name="PharmacySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, help_text="For walk-in customers", max_length=200
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("MOBILE", "Mobile Banking"),
                            ("INSURANCE", "Insurance"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "change_returned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_purchases",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_sales",
                        to="appointments.prescription",
                    ),
                ),
                (
                    "served_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pharmacy.drug"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.pharmacysale",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("RETURN", "Return to Supplier"),
                            ("EXPIRED", "Expired"),
                            ("DAMAGED", "Damaged"),
                            ("CORRECTION", "Stock Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for additions, negative for removals"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reason", models.TextField()),
                ("adjusted_at", models.DateTimeField(auto_now_add=True)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="pharmacy.drug",
                    ),
                ),
            ],
            options={
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["drug_code"], name="pharmacy_dr_drug_co_d009a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["generic_name"], name="pharmacy_dr_generic_ce7297_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["brand_name"], name="pharmacy_dr_brand_n_3ea4c0_idx"
            ),
        ),
    ]
