# Generated by Django 5.2.7 on 2025-11-09 17:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total appointment/service amount",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission percentage applied",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission amount (percentage of total)",
                        max_digits=10,
                    ),
                ),
                (
                    "admin_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount going to admin (remaining after commission)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_paid_to_member",
                    models.BooleanField(
                        default=False,
                        help_text="Has commission been paid to PC member?",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("DOCTOR", "Doctor"),
                            ("RECEPTIONIST", "Receptionist"),
                            ("LAB", "Lab Staff"),
                            ("PHARMACY", "Pharmacy Staff"),
                            ("CANTEEN", "Canteen Staff"),
                        ],
                        default="RECEPTIONIST",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "specialization",
                    models.CharField(
                        blank=True, help_text="For doctors", max_length=100
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, help_text="Professional license", max_length=50
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=300.0,
                        help_text="Default consultation fee for this doctor",
                        max_digits=10,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PCMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pc_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Member"),
                            ("LIFETIME", "Lifetime Member"),
                            ("INVESTOR", "Investor Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission percentage (e.g., 30 for 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total commission earned (paid amount)",
                        max_digits=12,
                    ),
                ),
                (
                    "due_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission amount due (not yet paid)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_referrals",
                    models.IntegerField(
                        default=0, help_text="Total number of referrals"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pc_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
