# Generated by Django 5.2.7 on 2025-11-09 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pctransaction",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="pctransaction",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="pctransaction",
            name="pc_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.pcmember",
            ),
        ),
        migrations.AddField(
            model_name="pctransaction",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pc_transactions_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pcmember",
            index=models.Index(
                fields=["pc_code"], name="accounts_pc_pc_code_93fd8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pcmember",
            index=models.Index(
                fields=["member_type"], name="accounts_pc_member__990e3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pctransaction",
            index=models.Index(
                fields=["transaction_date"], name="accounts_pc_transac_0d3828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pctransaction",
            index=models.Index(
                fields=["pc_member", "transaction_date"],
                name="accounts_pc_pc_memb_e9c863_idx",
            ),
        ),
    ]
