# Generated by Django 5.2.7 on 2025-10-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("LAB", "Lab Staff"),
                    ("PHARMACY", "Pharmacy Staff"),
                    ("CANTEEN", "Canteen Staff"),
                ],
                default="RECEPTIONIST",
                max_length=20,
            ),
        ),
    ]
