# Generated by Django 5.2.7 on 2025-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.TextField(blank=True, help_text='Educational qualifications'),
        ),
    ]
