# Generated by Django 5.2.7 on 2025-10-28 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20251027_0039"),
        ("appointments", "0004_alter_doctoravailability_options_and_more"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="qualification",
        ),
        migrations.CreateModel(
            name="PCMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pc_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Member"),
                            ("LIFETIME", "Lifetime Member"),
                            ("INVESTOR", "Investor Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission percentage (e.g., 30 for 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total commission earned",
                        max_digits=12,
                    ),
                ),
                (
                    "total_referrals",
                    models.IntegerField(
                        default=0, help_text="Total number of referrals"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pc_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PCTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total appointment/service amount",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission percentage applied",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission amount (percentage of total)",
                        max_digits=10,
                    ),
                ),
                (
                    "admin_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount going to admin (remaining after commission)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_paid_to_member",
                    models.BooleanField(
                        default=False,
                        help_text="Has commission been paid to PC member?",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.patient",
                    ),
                ),
                (
                    "pc_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.pcmember",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_transactions_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.AddIndex(
            model_name="pcmember",
            index=models.Index(
                fields=["pc_code"], name="accounts_pc_pc_code_93fd8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pcmember",
            index=models.Index(
                fields=["member_type"], name="accounts_pc_member__990e3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pctransaction",
            index=models.Index(
                fields=["transaction_date"], name="accounts_pc_transac_0d3828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pctransaction",
            index=models.Index(
                fields=["pc_member", "transaction_date"],
                name="accounts_pc_pc_memb_e9c863_idx",
            ),
        ),
    ]
