# Generated by Django 5.2.7 on 2025-10-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_qualification_pcmember_pctransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcmember",
            name="due_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Commission amount due (not yet paid)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="pcmember",
            name="total_commission_earned",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total commission earned (paid amount)",
                max_digits=12,
            ),
        ),
    ]
