# Generated by Django 5.2.7 on 2025-10-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_pcmember_due_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_fee',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                default=300.00,
                help_text='Default consultation fee for this doctor'
            ),
        ),
    ]
