# Generated by Django 5.2.7 on 2025-11-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_set_default_commission_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcmember",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Default commission percentage",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="pcmember",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Member"),
                    ("LIFETIME", "Lifetime Member"),
                    ("PREMIUM", "Premium Member"),
                ],
                max_length=20,
            ),
        ),
    ]
