# Generated by Django 5.2.7 on 2025-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_pcmember_commission_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcmember",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Default commission percentage (for other services)",
                max_digits=5,
            ),
        ),
    ]
