# Generated by Django 5.2.7 on 2025-11-09 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "serial_number",
                    models.IntegerField(help_text="Queue serial number for the day"),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("called_time", models.DateTimeField(blank=True, null=True)),
                ("started_time", models.DateTimeField(blank=True, null=True)),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("partial", "Partial"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("scheduled", "Scheduled"),
                            ("emergency", "Emergency"),
                        ],
                        default="walk_in",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for visit")),
                ("notes", models.TextField(blank=True)),
                ("room_number", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["appointment_date", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="False = doctor is unavailable on this date",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="e.g., On leave, Conference",
                        max_length=200,
                    ),
                ),
                ("max_patients", models.IntegerField(blank=True, null=True)),
                ("room_number", models.CharField(blank=True, max_length=20)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Doctor availabilities",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "max_patients",
                    models.IntegerField(
                        default=20, help_text="Maximum patients for this session"
                    ),
                ),
                (
                    "consultation_duration",
                    models.IntegerField(
                        default=15, help_text="Minutes per consultation"
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chief_complaint",
                    models.TextField(blank=True, help_text="Patient's main complaint"),
                ),
                ("history", models.TextField(blank=True, help_text="Medical history")),
                (
                    "on_examination",
                    models.TextField(
                        blank=True, help_text="Physical examination findings"
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, help_text="e.g., 140/70 mm Hg", max_length=20
                    ),
                ),
                (
                    "pulse",
                    models.CharField(
                        blank=True, help_text="e.g., 72/min", max_length=20
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        blank=True, help_text="e.g., 98.6°F", max_length=20
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="e.g., 60 kg", max_length=20
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Primary diagnosis")),
                (
                    "investigation",
                    models.TextField(
                        blank=True, help_text="Tests ordered (e.g., CBC, X-Ray)"
                    ),
                ),
                (
                    "advice",
                    models.TextField(
                        blank=True, help_text="Doctor's advice to patient"
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("is_printed", models.BooleanField(default=False)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printed_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                ("dosage", models.CharField(help_text="e.g., 500mg", max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., 1+0+1 (morning, noon, night)", max_length=100
                    ),
                ),
                (
                    "duration",
                    models.CharField(help_text="e.g., 7 days", max_length=100),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="e.g., After meal"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="appointments.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "doctor", "status"],
                name="appointment_appoint_d43bd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_number"], name="appointment_appoint_93abbc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "appointment_date", "serial_number")},
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together={("doctor", "date", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "day_of_week", "start_time")},
        ),
    ]
