# Generated by Django 5.2.7 on 2025-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_online_booking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="online_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("walk_in", "Walk-in"),
                    ("scheduled", "Scheduled"),
                    ("emergency", "Emergency"),
                    ("online", "Online Booking"),
                ],
                default="walk_in",
                max_length=20,
            ),
        ),
    ]
