# Generated by Django 5.2.7 on 2025-10-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_doctoravailability_doctor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctoravailability",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name_plural": "Doctor availabilities",
            },
        ),
        migrations.RemoveField(
            model_name="doctoravailability",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="doctorschedule",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="doctorschedule",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="doctorschedule",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="room_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="False = doctor is unavailable on this date"
            ),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="max_patients",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="reason",
            field=models.CharField(
                blank=True, help_text="e.g., On leave, Conference", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorschedule",
            name="consultation_duration",
            field=models.IntegerField(default=15, help_text="Minutes per consultation"),
        ),
        migrations.AlterField(
            model_name="doctorschedule",
            name="max_patients",
            field=models.IntegerField(
                default=20, help_text="Maximum patients for this session"
            ),
        ),
    ]
