# Generated by Django 5.2.7 on 2025-10-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_doctoravailability_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("walk_in", "Walk-in"),
                    ("scheduled", "Scheduled"),
                    ("emergency", "Emergency"),
                ],
                default="walk_in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("partial", "Partial"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
