# Generated by Django 5.2.7 on 2025-10-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_appointment_appointment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("called", "Called"),
                    ("in_consultation", "In Consultation"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
