# Generated by Django 5.2.7 on 2025-10-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="blood_pressure",
            field=models.CharField(
                blank=True, help_text="e.g., 140/70 mm Hg", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="history",
            field=models.TextField(blank=True, help_text="Medical history"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="investigation",
            field=models.TextField(
                blank=True, help_text="Tests ordered (e.g., CBC, X-Ray)"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="on_examination",
            field=models.TextField(
                blank=True, help_text="Physical examination findings"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="pulse",
            field=models.CharField(blank=True, help_text="e.g., 72/min", max_length=20),
        ),
        migrations.AddField(
            model_name="prescription",
            name="temperature",
            field=models.CharField(blank=True, help_text="e.g., 98.6°F", max_length=20),
        ),
        migrations.AddField(
            model_name="prescription",
            name="weight",
            field=models.CharField(blank=True, help_text="e.g., 60 kg", max_length=20),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="chief_complaint",
            field=models.TextField(blank=True, help_text="Patient's main complaint"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(help_text="Primary diagnosis"),
        ),
    ]
