# Generated by Django 5.2.7 on 2025-10-26 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_code", models.CharField(max_length=20, unique=True)),
                ("test_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood Test"),
                            ("URINE", "Urine Test"),
                            ("STOOL", "Stool Test"),
                            ("IMAGING", "Imaging"),
                            ("BIOCHEMISTRY", "Biochemistry"),
                            ("MICROBIOLOGY", "Microbiology"),
                            ("PATHOLOGY", "Pathology"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sample_type",
                    models.CharField(help_text="e.g., Blood, Urine", max_length=100),
                ),
                (
                    "sample_volume",
                    models.CharField(
                        blank=True, help_text="Required volume", max_length=50
                    ),
                ),
                (
                    "preparation_instructions",
                    models.TextField(blank=True, help_text="e.g., Fasting required"),
                ),
                (
                    "turnaround_time",
                    models.CharField(
                        help_text="e.g., 24 hours, Same day", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["test_name"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("SAMPLE_COLLECTED", "Sample Collected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ORDERED",
                        max_length=20,
                    ),
                ),
                ("sample_collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True, help_text="Clinical information from doctor"
                    ),
                ),
                (
                    "priority",
                    models.BooleanField(default=False, help_text="Mark as urgent"),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_lab_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "sample_collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tests",
                    models.ManyToManyField(related_name="orders", to="lab.labtest"),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        default=dict,
                        help_text="Store test parameters and values as JSON",
                    ),
                ),
                ("interpretation", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="lab_reports/"),
                ),
                ("is_printed", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lab.laborder",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lab.labtest"
                    ),
                ),
            ],
            options={
                "ordering": ["-tested_at"],
            },
        ),
    ]
