# Generated by Django 5.2.7 on 2025-11-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_pcmember_commission_percentage_and_more"),
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laborder",
            name="pc_member",
        ),
        migrations.AddField(
            model_name="laborder",
            name="pc_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_orders",
                to="accounts.pcmember",
            ),
        ),
    ]
