# Generated by Django 5.2.7 on 2025-10-26 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("emergency_contact_relation", models.CharField(max_length=50)),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="List of known allergies"),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True, help_text="List of chronic conditions"
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "chief_complaint",
                    models.TextField(help_text="Main reason for visit"),
                ),
                ("symptoms", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°F",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("blood_pressure_systolic", models.IntegerField(blank=True, null=True)),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "pulse_rate",
                    models.IntegerField(blank=True, help_text="bpm", null=True),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient Histories",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["patient_id"], name="patients_pa_patient_927c52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone"], name="patients_pa_phone_fc49bb_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["registered_at"], name="patients_pa_registe_f29344_idx"
            ),
        ),
    ]
